# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GO-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GO-iOS
  pod 'SwiftSocket'

  target 'GO-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GO-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
